### ISSUE TITLE
Why 2030?

### ISSUE THREAD

**Issue by CumpsD** [ArgonPrototypes/enix-clock#7]
https://github.com/ArgonPrototypes/enix-clock/blob/4bc53443660d4284ea7fa6f28d79d87a8610d30d/SOFTWARE/EnixClockFirmware.ino#L581

What's the deal with 2030 as the upper bound for the year? Is it a hardware limitation?

**Comment by marianoelia** [comment]
Fairly arbitrary really! The purpose of setting the year is only to check if it is a leap year, which adds 1 day to February. I thought about having a toggle for the leap year (0/1) but then people would have to google it and what not. Since I only have an increment button, I chose 2030 which is not too much of a hassle to cycle through if someone accidentally changes it. The only hardware limitation for leap year detection is 2100 on the DS3231M Real Time Clock chip.

**Comment by CumpsD** [comment]
Makes sense, thanks!
